info:
  contact: {}
paths:
  /get/{id}:
    get:
      consumes:
      - application/json
      description: Get a file of a photo from storage by id
      parameters:
      - description: Photo id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a photo
      tags:
      - Photos
  /presigned/get/{id}:
    get:
      consumes:
      - application/json
      description: Get a presigned url to a photo from storage by id
      parameters:
      - description: Photo id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a presigned url to a photo
      tags:
      - Photos
  /presigned/upload:
    get:
      consumes:
      - multipart/form-data
      description: Gets a presigned url to upload a photo to MinIO storage
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a presigned url to upload a photo
      tags:
      - Photos
swagger: "2.0"
